name: Deploy static site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Clean GitHub Pages branch before deploy
        run: rm -rf gh-pages-check

      - name: Generate config.json with API Key
        run: |
          echo "{\"API_KEY\": \"${{ secrets.INDIGITALL_API_KEY }}\"}" > ./dist/config.json
      
      - name: Inject API Key into index.html
        run: |
          sed -i 's|<!-- INJECT_API_KEY -->|<script>window.INDIGITALL_API_KEY = "${{ secrets.INDIGITALL_API_KEY }}";</script>|' ./dist/index.html

      - name: Verify index.html after injection
        run: cat ./dist/index.html | grep "window.INDIGITALL_API_KEY"

      - name: Copy indigitall folder to dist
        run: cp -r indigitall ./dist/indigitall
        
      - name: Disable Jekyll (allow serving JSON files)
        run: touch ./dist/.nojekyll

      - name: List files in dist/ and check if index.html exists
        run: |
          echo "Listing files in dist/"
          ls -l ./dist
          echo "Trying to cat index.html:"
          cat ./dist/index.html || echo "index.html not found"

      - name: List files after build
        run: ls -R ./dist | grep -v '^./node_modules/' # Check the files in the build folder

      - name: List dist/ folder
        run: ls -l ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false  # Ensures existing files are NOT deleted

      - name: Check published files
        run: |
          git clone --depth=1 --branch gh-pages https://github.com/mjrivera682/static-web-page.git gh-pages-check
          echo "📂 Archivos en gh-pages después del deploy:"
          find gh-pages-check -type f
